config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path("", include("posts.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

posts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from posts.views import (
    AcceptProposalView,
    ExchangeProposalCreateView,
    LogoutRedirectView,
    MyPostsListView,
    MyProposalsListView,
    PostCreateView,
    PostDeleteView,
    PostListView,
    PostUpdateView,
    RejectProposalView,
)

app_name = "posts"

urlpatterns = [
    path(
        "",
        PostListView.as_view(),
        name="posts_list",
    ),
    path(
        "create/",
        PostCreateView.as_view(),
        name="create_post",
    ),
    path(
        "my_posts/",
        MyPostsListView.as_view(),
        name="my_posts",
    ),
    path(
        "proposals/",
        MyProposalsListView.as_view(),
        name="proposals",
    ),
    path(
        "proposals/create/",
        ExchangeProposalCreateView.as_view(),
        name="proposal_create",
    ),
    path(
        "proposals/<int:pk>/accept/",
        AcceptProposalView.as_view(),
        name="proposal_accept",
    ),
    path(
        "proposals/<int:pk>/reject/",
        RejectProposalView.as_view(),
        name="proposal_reject",
    ),
    path(
        "my_posts/<int:pk>/delete/",
        PostDeleteView.as_view(),
        name="delete_post",
    ),
    path(
        "my_posts/<int:pk>/",
        PostUpdateView.as_view(),
        name="edit_post",
    ),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            next_page="/",
        ),
        name="login",
    ),
    path(
        "logout/",
        LogoutRedirectView.as_view(),
        name="logout",
    ),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    class CATEGORY_CHOICES(models.TextChoices):
        BOOKS = "books", "Книги"
        ELECTRONICS = "electronics", "Электроника"
        CLOTH = "cloth", "Одежда"
        FURNITURE = "furniture", "Мебель"
        OTHER = "other", "Другое"

    class CONDITION_CHOICES(models.TextChoices):
        NEW = "new", "Новое"
        LIKE_NEW = "like new", "Как новое"
        USED = "used", "Б/У"
        FOR_PARTS = "for parts", "На запчасти"

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
    )
    title = models.CharField(
        "Название",
        max_length=255,
    )
    description = models.TextField(
        "Описание",
        blank=True,
    )
    image = models.ImageField(
        "Картинка",
        upload_to="images/",
        blank=True,
        help_text="Загрузите картинку",
    )
    category = models.CharField(
        "Категория",
        max_length=50,
        choices=CATEGORY_CHOICES,
    )
    condition = models.CharField(
        "Состояние",
        max_length=50,
        choices=CONDITION_CHOICES,
    )
    created_at = models.DateTimeField(
        "Дата создания",
        auto_now_add=True,
    )

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Объявление"
        verbose_name_plural = "Объявления"


class STATUS_CHOICES(models.TextChoices):
    PENDING = "pending", "На рассмотрении"
    ACCEPTED = "accepted", "Принято"
    REJECTED = "rejected", "Отклонено"


class ExchangeProposal(models.Model):
    sender = models.ForeignKey(
        "Post", on_delete=models.CASCADE, related_name="sent_proposals"
    )
    receiver = models.ForeignKey(
        "Post", on_delete=models.CASCADE, related_name="received_proposals"
    )
    comment = models.TextField("Комментарий")
    status = models.CharField(
        "Статус",
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_CHOICES.PENDING,
    )
    created_at = models.DateTimeField(
        "Дата создания",
        auto_now_add=True,
    )

    def __str__(self) -> str:
        return f"Обмен от {self.sender} на {self.receiver} ({self.status})"

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Предложение обмена"
        verbose_name_plural = "Предложения обмена"

templates/proposals/filter.html
<section>
    <form method="get" action="{% url 'posts:proposals' %}">
        <div>
            <label for="receiver">Получатель:</label>
            <select id="receiver" name="receiver">
                <option value=""></option>
                {% for receiver in receivers %}
                    <option value="{{ receiver.id }}">{{ receiver.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="sender">Отправитель:</label>
            <select id="sender" name="sender">
                <option value=""></option>
                {% for sender in senders %}
                    <option value="{{ sender.id }}">{{ sender.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="status">Статус:</label>
            <select id="status" name="status">
                <option value=""></option>
                {% for status in statuses %}
                    <option value="{{ status.value }}">{{ status.label }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit">Искать</button>
        <a href="{% url "posts:proposals" %}" role="button">Сбросить фильтры</a>
    </form>
</section>

templates/proposals/my_proposals_list.html
{% extends "base.html" %}
{% block content %}
    {% if proposals %}
        <ul class="grow">
            {% for proposal in proposals %}
                <section>
                    {% if proposal.sender.image %}
                        <img src="{{ proposal.sender.image.url }}"
                             alt="Изображение товара"
                             width="auto"
                             height="350">
                    {% endif %}
                    <br>
                    <strong>Обмен:</strong> {{ proposal.sender.title }}
                    <br>
                    <strong>На:</strong> {{ proposal.receiver.title }}
                    <br>
                    <strong>Получатель:</strong> {{ proposal.receiver.user.username }}
                    <br>
                    <strong>Отправитель:</strong> {{ proposal.sender.user.username }}
                    <br>
                    <strong>Комментарий:</strong> {{ proposal.comment }}
                    <br>
                    <strong>Статус:</strong> {{ proposal.get_status_display }}
                    <br>
                    <strong>Дата:</strong> {{ proposal.created_at|date:"d.m.Y H:i" }}
                    <br>
                    <menu>
                        {% if user == proposal.receiver.user and proposal.status == 'pending' %}
                            <li>
                                <form method="post" action="{% url 'posts:proposal_accept' proposal.pk %}">
                                    {% csrf_token %}
                                    <button type="submit">Принять</button>
                                </form>
                            </li>
                            <li>
                                <form method="post" action="{% url 'posts:proposal_reject' proposal.pk %}">
                                    {% csrf_token %}
                                    <button type="submit">Отклонить</button>
                                </form>
                            </li>
                        {% endif %}
                    </menu>
                </section>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нету ни одного предложения обмена.</p>
    {% endif %}
{% endblock content %}
{% comment %} {% extends "base.html" %}
{% block content %}
    {% if proposals %}
        <table class="center">
            <thead>
                <tr>
                    <th>Обмен</th>
                    <th>На</th>
                    <th>Получатель</th>
                    <th>Отправитель</th>
                    <th>Комментарий</th>
                    <th>Статус</th>
                    <th>Дата</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for proposal in proposals %}
                    <tr>
                        <td>{{ proposal.sender.title }}</td>
                        <td>{{ proposal.receiver.title }}</td>
                        <td>{{ proposal.receiver.user.username }}</td>
                        <td>{{ proposal.sender.user.username }}</td>
                        <td>{{ proposal.comment }}</td>
                        <td>{{ proposal.get_status_display }}</td>
                        <td>{{ proposal.created_at|date:"d.m.Y H:i" }}</td>
                        <td>
                            {% if user == proposal.receiver.user and proposal.status == 'pending' %}
                                <form method="post" action="{% url 'posts:proposal_accept' proposal.pk %}">
                                    {% csrf_token %}
                                    <button type="submit">👍</button>
                                </form>
                                <form method="post" action="{% url 'posts:proposal_reject' proposal.pk %}" class="grow">
                                    {% csrf_token %}
                                    <button type="submit">👎</button>
                                </form>
                            {% else %}
                                <em>Нет действий</em>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Нету ни одного предложения обмена.</p>
    {% endif %}
{% endblock content %} {% endcomment %}

templates/proposals/proposal_form.html
{% extends "base.html" %}
{% block content %}
    <form method="post" class="grow">
        {% csrf_token %}
        <div>
            <label for="sender_post_id">Выберите одно из ваших объявлений:</label>
            <select name="sender_post_id" required>
                {% for post in user.posts.all %}<option value="{{ post.id }}">{{ post.title }}</option>{% endfor %}
            </select>
        </div>
        {{ form.as_p }}
        <button type="submit">Отправить предложение</button>
    </form>
{% endblock content %}